config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "about" => "public#about", as: :about
  #get "about" can also be written as
  #get "about", controller: "public", action: "about",as: :about
  get "blog" => "public#blog", as: :blog
  # get "blog", controller: "public", action: "blog",as: :blog
  get "public" => "public#contact", as: :contact

  post "post/view" => "posts#save_post_view", as: :post_view
  root to: "public#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title, :url

  has_many :posts

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :summary, presence: true
  validates :body, presence: true

  belongs_to :category

#callbacks validation/save/create/update/destroy

  after_create :update_total_post_count

  scope :active, -> { where(active: true) }
  scope :order_by_latest_first, -> { order(created_at: :desc)}
  scope :limit_2, -> { limit( 2 )}


  private

  def update_total_post_count
    #update_category total count column to show total posts count
    category.increment(:total_count,1).save
  end

  def details
    "This post was created on #{ created_at.strftime("%d/%m/%Y") }."
  end

  def self.total
    #returns a  total number of posts
    count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy save_post_view ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    respond_to do |format|
      format.html
      format.json {
        render json: @post
      }
      format.text {
        render plain: @post.title
      }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
      if @post.save
        redirect_to @post, notice: "Post was successfully created."
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, notice: "Post was successfully updated."
      else
        render :edit
      end
  end


  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
      redirect_to posts_url, notice: "Post was successfully destroyed."
  end



  def save_post_view
    # increment view count for post
    @post.increment(:views, 1).save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :summary, :body, :active, :category_id)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def homepage
    @posts = Post.active.order_by_latest_first.limit_2
    @categories = Category.all
  end

  def about
  end

  def blog

  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title title
    content_for :page_title, title.to_s
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/helpers/posts_helper.rb
module PostsHelper
  def post_meta post
    "Created  #{time_ago_in_words(post.created_at) }  ago in  #{post.category.title} . Post has been viewed: #{post.views} times."
  end
end

app/views/layouts/_footer.html.erb
<div class="container bg-white">
  <div class="row">
    <footer class="s-footer">

      <div class="row s-footer__top">
        <div class="column">
          <ul class="s-footer__social">
            <li><a href="https://www.facebook.com/madhur.shrestha.984"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="https://twitter.com/killervikingss"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="https://www.youtube.com/channel/UCOzTU7GFeymNZkuPW7yKrZA"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
            <li><a href="https://github.com/MadhurShrestha"><i class="fab fa-github" aria-hidden="true"></i></a></li>
            <li><a href="https://www.instagram.com/peakyblindersofficial/"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href="https://www.linkedin.com/in/aayushstha17/"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
          </ul>
        </div>
      </div> <!-- end footer__top -->
        <div class="row s-footer__bottom">

            <div class="large-6 tab-full column s-footer__info">
                <h3 class="h6">About this Blog</h3>
                <p>
                  This blog is made with Keep It Simple template. It is being updated to a working blog from the skillshare project by David Battersby.This project is being turned into a dynamic website slowly.
                </p>
                <p>
                  There are different types of article in these blogs. These are created by different writers.If you want to support these writers. Donate to your local charities near you.
                </p>
            </div>

            <div class="large-6 tab-full column">
              <div class="row">
                <div class="large-8 tab-full column">
                  <h3 class="h6">Photostream</h3>
                    <ul class="photostream group">
                      <li><a href="#0"><img alt="thumbnail" src="thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                      <li><a href="#0"><img alt="thumbnail" src="images/thumb.jpg"></a></li>
                    </ul>
                  </div>
                  <div class="large-3 tab-full column">
                    <h3  class="h6">Navigate</h3>
                    <ul class="s-footer__list s-footer-list--nav group">
                      <li><%= link_to "Home",root_path %></li>
                      <li><%= link_to"About",about_path %></li>
                      <li><%= link_to "Blog",blog_path %></li>
                      <li><%= link_to "Contact",contact_path %></li>
                    </ul>
                  </div>
              </div>
            </div>

            <div class="ss-copyright">
                <span>Copyright &copy; <%= Date.current.strftime("%Y") %> Blog App</span>
                <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
            </div>

        </div> <!-- end footer__bottom -->
         <div class="ss-go-top">
            <a class="smoothscroll" title="Back to Top" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"/></svg>
            </a>
        </div> <!-- end ss-go-top -->
    </footer>
  </div>
</div>

app/views/layouts/_form_validation.html.erb
  <% if local_assigns[:item] && item.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_menu.html.erb
<h1 class="float-start" id="site-name">Blog App</h1>

  <header class="s-header">
    <div class="row">
      <div class="s-header__content column">
          <h1 class="s-header__logotext">
          <a class="current"><%= link_to "Blog It",root_path %></a>
          </h1>
          <p class="s-header__tagline">Your thoughts into words.</p>
      </div>
    </div> <!-- end row -->

     <nav class="s-header__nav-wrap">
       <div class="row">
        <ul class="s-header__nav">
          <li class="current"><%= link_to "Home",root_path %></li>
            <li class="has-children"><a href="#0">Dropdown</a>
              <ul>
                <li><a href="#0">History</a></li>
                <li><a href="#0">Present</a></li>
                <li><a href="#0">Future</a></li>
            </ul>
            </li>
          <li><%= link_to"About",about_path %></li>
          <li><%= link_to "Contact",contact_path %></li>
            <li class="has-children"><a href="#0">Blog</a>
              <ul>
                <li><a href="blog.html">Blog Entries</a></li>
                  <li><%= link_to "Blog",blog_path %></li>
              </ul>
            </li>
        </ul> <!-- end #nav -->
     </div>
    </nav> <!-- end #nav-wrap -->

      <a class="header-menu-toggle" href="#0" title="Menu"><span>Menu</span></a>

  </header> <!-- Header End -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : "Ruby On Rails" %> | Blog app</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

     <script src="https://kit.fontawesome.com/2cd7f5bf2c.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag "apple-touch-icon.png",sizes: "180*180",rel: "icon"%>
    <%= favicon_link_tag "favicon-32x32.png",sizes: "32*32"%>
    <%= favicon_link_tag "favicon-16x16.png",sizes: "16*16"%>
      </head>

  <body>

    <div class="container bg-white">
      <div class="row">
        <div class="col page-nav">
        <%= render partial: "layouts/menu" %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <div class="col page-nav">
        <%= render partial: "layouts/body" %>
        </div>
      </div>


    </div>

    <%= render partial: 'layouts/footer' %>






    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <%= yield(:scripts) if content_for?(:scripts) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render partial: "layouts/form_validation", locals: {item: post} %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect{ |c| [c.title, c.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p class="h1"><%= link_to post.title,post_path(post) %></p>

<h7><%= post_meta post %></h7>

<p class="h1">  <%= post.summary %></p>

app/views/posts/_view_form.html.erb
<%= form_with(url: post_view_path, html: {id: "save_views"}) do |form| %>

  <%= form.hidden_field :id, value: post.id %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Body</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.summary %></td>
        <td><%= post.body %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
  <large>
    <%= post_meta @post %>
  </large>
</p>

<%= simple_format @post.body %>

<%= render partial: "posts/view_form", locals: { post: @post }%>